Import("env")

env["CPPPATH"] = ["#include"]

env["LIBS"] = ["common", "rt"]
env["LIBPATH"] = ["../src/common"]

env.ParseConfig(env["CONFIG_PARSER"])

# Unit tests for libcommon
env.Program("strlist_test", ["strlist_test.c"])
env.Program("timespan_test", ["timespan_test.c"])
